### PR TITLE
Adding Russian translation

### PR DESCRIPTION
**Pull request by Atrafon**

### CODE REVIEW

**Comment by ammargitham** [comment]
Hey. Thanks for the translations 🙂.

**Comment by ammargitham** [comment]
The CodeQL is failing with an error regarding the xml format. Let me check this later locally. Then I'll merge the PR.

**Comment by ammargitham** [comment]
@Atrafon Can you merge [this commit](https://github.com/ammargitham/WallFlow/commit/3858ea4ddcd8de60f9cc28a79fa8c9407b9faa12) (or copy the changes).

It fixes the xml tags and the plurals required for Russian language.
Also I added some missing strings, please translate those too.

**Comment by Atrafon** [comment]
@ammargitham OK. I'll do it when I'm home.

**Comment by Atrafon** [comment]
@ammargitham missing strings translated, fixed plurals translation. PR is ready.

**Pull request merged**
